get-image-and-run-command: Add better messaging to detect potential user error

diff --git a/get-image-and-run-command/action.yml b/get-image-and-run-command/action.yml
--- a/get-image-and-run-command/action.yml
+++ b/get-image-and-run-command/action.yml
@@ -21,24 +21,29 @@ inputs:
   checkout:
     description: "Whether to check out the repository"
     required: false
+  show-output-on-success:
+    description: "Whether to show the output from the command on success in the job summary"
+    required: false
 
 runs:
   using: 'composite'
   steps:
     - name: Validate inputs
-      if: ${{ !inputs.image || !inputs.workload-identity-provider != !inputs.service-account || (inputs.checkout == 'true' && !inputs.service-account) }}
+      if: ${{ !inputs.image || !inputs.workload-identity-provider != !inputs.service-account }}
       shell: bash
       env:
         INPUTS: ${{ toJSON(inputs) }}
-        CODEPENDENT: '[ [ "workload-identity-provider", "service-account" ], [ "checkout", "service-account" ] ]'
+        CODEPENDENT: ${{ inputs.checkout == 'true' && '[ [ "workload-identity-provider", "service-account" ], [ "checkout", "service-account" ], [ "checkout", "workload-identity-provider" ] ]' || '[ [ "workload-identity-provider", "service-account" ], [ "checkout", "service-account" ] ]' }}
       run: |
         "$GITHUB_ACTION_PATH/../scripts/report-missing-inputs.pl"
 
     - name: Checkout
+      id: checkout
       if: ${{ inputs.checkout == 'true' }}
       uses: actions/checkout@v4
 
     - name: Set up google docker credentials
+      id: google-credentials
       if: ${{ inputs.workload-identity-provider && inputs.service-account }}
       uses: GarnerCorp/build-actions/configure-google-docker@main
       env:
@@ -55,10 +60,32 @@ runs:
       env:
         IMAGE: ${{ inputs.image }}
         CMD: ${{ inputs.command }}
+        CHECKOUT_OVERWRITE: ${{ steps.checkout.conclusion == 'success' && steps.google-credentials.conclusion == 'skipped' && env.GOOGLE_GHA_CREDS_PATH && '1' || '' }}
+        NO_WIP: ${{ inputs.workload_identity_provider == '' && '1' || '' }}
+        NO_SA: ${{ inputs.service-account == '' && '1' || '' }}
+        SHOW_OUTPUT_ON_SUCCESS: ${{ inputs.show-output-on-success }}
       shell: bash
       run: |
         : 'Run command and report errors'
-        docker pull "$IMAGE"
+        if docker pull "$IMAGE"; then
+          :
+        else
+           exit_code="$?"
+           if [ -n "$CHECKOUT_OVERWRITE" ]; then
+             (
+                echo "# docker pull '$IMAGE' failed"
+                echo '`inputs.checkout` was set, but a step before this action used google-github-actions/auth'
+                echo 'you probably do not want to use `inputs.checkout`, or '
+                echo "you need to use ${NO_WIP:+\`inputs.workload-identity-provider\` ${NO_SA:+and }}${NO_SA:+\`inputs.service-account\`}"
+             ) >> "$GITHUB_STEP_SUMMARY"
+           else
+             (
+                echo "# docker pull '$IMAGE' failed"
+                echo "sorry, that's all we know"
+             ) >> "$GITHUB_STEP_SUMMARY"
+           fi
+           exit $exit_code
+        fi
 
         stdout_file=$(mktemp)
         stderr_file=$(mktemp)
@@ -75,7 +102,9 @@ runs:
         }
 
         if bash -c "$CMD" > "$stdout_file" 2> "$stderr_file"; then
-          :
+          if [ "$SHOW_OUTPUT_ON_SUCCESS" == "true" ]; then
+            summarize output $stdout_file
+          fi
         else
           exit_code="$?"
           summarize output $stdout_file
